name: Github actions demo
on:
  [pull-requests]
    branches: [main]
  workflow_dispatch:
  
jobs:
  
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout user repo
        uses: actions/checkout@v2
      
      - name: checking lint on Dockerfile
        uses: hadolint/hadolint-action@v1.5.0
          with:
            dockerfile: Dockerfile
            
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        
      - name: try to build flask-app
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: false
          tags: chary1825/flask-app:latest
